spring:
  application:
    name: Climby API

  flyway:
    enabled: true
    validate-on-migrate: true

  jpa:
    hibernate:
      ddl-auto: validate

  datasource:
    url: ${DB_URL:jdbc:mariadb://localhost:3306/climby_db}
    username: ${DB_USERNAME:dev}
    password: ${DB_PASSWORD:changeMe}
    driver-class-name: org.mariadb.jdbc.Driver

okta:
  oauth2:
    issuer: ${OAUTH2_ISSUER}
    audience: ${OAUTH2_AUDIENCE}
